export type Worker = {
  id: number;
  name: Record<string, string>;
  skill: string; // skill key e.g. "Mason"
  village: Record<string, string>;
  taluk: Record<string, string>;
  district: Record<string, string>;
  experience: number;
  availability: "Available" | "Busy";
  phone: string;
  languages: string[];
  workingHours: string;
  description: Record<string, string>;
  avatar: string;
};

export type HireRequest = {
  id: number;
  employerName: Record<string, string>;
  workType: string;
  location: Record<string, string>;
  date: string;
  status: "pending" | "accepted" | "rejected" | "expired";
  message: Record<string, string>;
};

export type Language = "en" | "kn" | "hi";

export type Page =
  | "landing"
  | "register-worker"
  | "find-workers"
  | "worker-profile"
  | "worker-dashboard"
  | "login"
  | "signup"
  | "about";

// Skill keys are always English internally; display is translated via getSkillLabel()
export const SKILL_KEYS = [
  "Mason",
  "Electrician",
  "Plumber",
  "Painter",
  "Carpenter",
  "Tailoring",
  "Chef",
  "Cleaner",
  "Mechanic",
  "Labour",
  "Other",
];

export const SKILL_LABELS: Record<string, Record<Language, string>> = {
  Mason:       { en: "Mason",        kn: "ಕಟ್ಟಡ ಕೆಲಸಗಾರ",      hi: "राजमिस्त्री" },
  Electrician: { en: "Electrician",  kn: "ವಿದ್ಯುತ್ ತಜ್ಞ",       hi: "बिजली मिस्त्री" },
  Plumber:     { en: "Plumber",      kn: "ಪ್ಲಂಬರ್",             hi: "प्लंबर" },
  Painter:     { en: "Painter",      kn: "ಬಣ್ಣ ಕೆಲಸಗಾರ",        hi: "पेंटर" },
  Carpenter:   { en: "Carpenter",    kn: "ಮರಗೆಲಸಗಾರ",           hi: "बढ़ई" },
  Tailoring:   { en: "Tailoring",    kn: "ಹೊಲಿಗೆ",              hi: "दर्जी" },
  Chef:        { en: "Chef",         kn: "ಅಡುಗೆಯವರು",           hi: "रसोइया" },
  Cleaner:     { en: "Cleaner",      kn: "ಸ್ವಚ್ಛಗೊಳಿಸುವವರು",   hi: "सफाईकर्मी" },
  Mechanic:    { en: "Mechanic",     kn: "ಮೆಕ್ಯಾನಿಕ್",           hi: "मैकेनिक" },
  Labour:      { en: "Labour",       kn: "ಕೂಲಿ ಕೆಲಸ",           hi: "मजदूर" },
  Other:       { en: "Other",        kn: "ಇತರೆ",                hi: "अन्य" },
};

export const getSkillLabel = (key: string, lang: Language): string =>
  SKILL_LABELS[key]?.[lang] ?? key;

export const TALUK_OPTIONS_KEYS = [
  "all",
  "Udupi",
  "Mangalore",
  "Bantwal",
  "Puttur",
  "Sullia",
  "Belthangady",
  "Karkala",
];

export const TALUK_LABELS: Record<string, Record<Language, string>> = {
  all:         { en: "All Taluks",   kn: "ಎಲ್ಲಾ ತಾಲೂಕುಗಳು",  hi: "सभी तालुक" },
  Udupi:       { en: "Udupi",        kn: "ಉಡುಪಿ",             hi: "उडुपी" },
  Mangalore:   { en: "Mangalore",    kn: "ಮಂಗಳೂರು",           hi: "मंगलुरु" },
  Bantwal:     { en: "Bantwal",      kn: "ಬಂಟ್ವಾಳ",           hi: "बंटवाल" },
  Puttur:      { en: "Puttur",       kn: "ಪುತ್ತೂರು",          hi: "पुत्तूर" },
  Sullia:      { en: "Sullia",       kn: "ಸುಳ್ಯ",              hi: "सुल्ल्या" },
  Belthangady: { en: "Belthangady",  kn: "ಬೆಳ್ತಂಗಡಿ",         hi: "बेलतंगडी" },
  Karkala:     { en: "Karkala",      kn: "ಕಾರ್ಕಳ",            hi: "कारकल" },
};

export const EXPERIENCE_OPTIONS_KEYS = [
  "any",
  "0-1",
  "1-3",
  "3-5",
  "5+",
];
export const EXPERIENCE_LABELS: Record<string, Record<Language, string>> = {
  any: { en: "Any Experience", kn: "ಯಾವುದೇ ಅನುಭವ",   hi: "कोई भी अनुभव" },
  "0-1": { en: "0–1 years",   kn: "0–1 ವರ್ಷ",        hi: "0–1 वर्ष" },
  "1-3": { en: "1–3 years",   kn: "1–3 ವರ್ಷ",        hi: "1–3 वर्ष" },
  "3-5": { en: "3–5 years",   kn: "3–5 ವರ್ಷ",        hi: "3–5 वर्ष" },
  "5+":  { en: "5+ years",    kn: "5+ ವರ್ಷ",         hi: "5+ वर्ष" },
};

export const AVAILABILITY_KEYS = ["any", "Available", "Busy"];
export const AVAILABILITY_LABELS: Record<string, Record<Language, string>> = {
  any:       { en: "Any",       kn: "ಯಾವುದಾದರೂ", hi: "कोई भी" },
  Available: { en: "Available", kn: "ಲಭ್ಯ",       hi: "उपलब्ध" },
  Busy:      { en: "Busy",      kn: "ಬ್ಯುಸಿ",      hi: "व्यस्त" },
};

export const MOCK_WORKERS: Worker[] = [
  {
    id: 1,
    name: { en: "Ravi Poojary", kn: "ರವಿ ಪೂಜಾರಿ", hi: "रवि पूजारी" },
    skill: "Mason",
    village: { en: "Padubidri", kn: "ಪಾದುಬಿದ್ರಿ", hi: "पादुबिद्री" },
    taluk:   { en: "Udupi",     kn: "ಉಡುಪಿ",       hi: "उडुपी" },
    district:{ en: "Udupi",     kn: "ಉಡುಪಿ",       hi: "उडुपी" },
    experience: 8,
    availability: "Available",
    phone: "+91 94483 21056",
    languages: ["Kannada", "Tulu", "Hindi"],
    workingHours: "7 AM – 6 PM",
    description: {
      en: "Experienced mason specializing in brick laying, plastering, and concrete work. Available for both residential and commercial projects.",
      kn: "ಇಟ್ಟಿಗೆ ಹಾಕುವ, ಗಾರೆ ಕೆಲಸ ಮತ್ತು ಕಾಂಕ್ರೀಟ್ ಕೆಲಸದಲ್ಲಿ ನಿಪುಣ ಅನುಭವಿ ಕಟ್ಟಡ ಕೆಲಸಗಾರ. ವಸತಿ ಮತ್ತು ವಾಣಿಜ್ಯ ಯೋಜನೆಗಳಿಗೆ ಲಭ್ಯ.",
      hi: "ईंट बिछाने, प्लास्टरिंग और कंक्रीट कार्य में विशेषज्ञ अनुभवी राजमिस्त्री। आवासीय और व्यावसायिक दोनों परियोजनाओं के लिए उपलब्ध।",
    },
    avatar: "RP",
  },
  {
    id: 2,
    name: { en: "Anita Dsouza", kn: "ಅನಿತಾ ಡಿಸೋಜಾ", hi: "अनिता डिसूजा" },
    skill: "Tailoring",
    village: { en: "Bolar",     kn: "ಬೋಳಾರ",    hi: "बोलार" },
    taluk:   { en: "Mangalore", kn: "ಮಂಗಳೂರು", hi: "मंगलुरु" },
    district:{ en: "Dakshina Kannada", kn: "ದಕ್ಷಿಣ ಕನ್ನಡ", hi: "दक्षिण कन्नड" },
    experience: 5,
    availability: "Available",
    phone: "+91 98452 67321",
    languages: ["Kannada", "Konkani", "English"],
    workingHours: "9 AM – 5 PM",
    description: {
      en: "Skilled tailor with expertise in traditional and modern clothing. Specializes in sarees, salwar kameez, and school uniforms.",
      kn: "ಸಾಂಪ್ರದಾಯಿಕ ಮತ್ತು ಆಧುನಿಕ ಉಡುಪುಗಳಲ್ಲಿ ಪರಿಣತಿ ಹೊಂದಿರುವ ನಿಪುಣ ಹೊಲಿಗೆ ಕೆಲಸಗಾರ. ಸೀರೆ, ಸಲ್ವಾರ್ ಕಮೀಜ್ ಮತ್ತು ಶಾಲಾ ಸಮವಸ್ತ್ರಗಳಲ್ಲಿ ತಜ್ಞರು.",
      hi: "पारंपरिक और आधुनिक कपड़ों में विशेषज्ञता वाली कुशल दर्जी। साड़ी, सलवार कमीज़ और स्कूल यूनिफॉर्म में माहिर।",
    },
    avatar: "AD",
  },
  {
    id: 3,
    name: { en: "Ganesh Bhat", kn: "ಗಣೇಶ್ ಭಟ್", hi: "गणेश भट्ट" },
    skill: "Chef",
    village: { en: "Nehru Nagar", kn: "ನೆಹರು ನಗರ", hi: "नेहरू नगर" },
    taluk:   { en: "Puttur",      kn: "ಪುತ್ತೂರು",  hi: "पुत्तूर" },
    district:{ en: "Dakshina Kannada", kn: "ದಕ್ಷಿಣ ಕನ್ನಡ", hi: "दक्षिण कन्नड" },
    experience: 12,
    availability: "Busy",
    phone: "+91 97423 88102",
    languages: ["Kannada", "Tulu"],
    workingHours: "6 AM – 2 PM",
    description: {
      en: "Expert chef specializing in Udupi cuisine, South Indian meals, and catering services. Available for events, functions, and daily cooking.",
      kn: "ಉಡುಪಿ ಅಡುಗೆ, ದಕ್ಷಿಣ ಭಾರತೀಯ ಊಟ ಮತ್ತು ಕೇಟರಿಂಗ್ ಸೇವೆಗಳಲ್ಲಿ ತಜ್ಞ ಅಡುಗೆಯವರು. ಕಾರ್ಯಕ್ರಮಗಳು, ಸಮಾರಂಭಗಳು ಮತ್ತು ದಿನನಿತ್ಯದ ಅಡುಗೆಗೆ ಲಭ್ಯ.",
      hi: "उडुपी व्यंजन, दक्षिण भारतीय भोजन और कैटरिंग सेवाओं में विशेषज्ञ रसोइया। कार्यक्रमों और दैनिक खाना पकाने के लिए उपलब्ध।",
    },
    avatar: "GB",
  },
  {
    id: 4,
    name: { en: "Manjula Nayak", kn: "ಮಂಜುಳ ನಾಯಕ್", hi: "मंजुला नायक" },
    skill: "Cleaner",
    village: { en: "Sullia Town", kn: "ಸುಳ್ಯ ಪಟ್ಟಣ", hi: "सुल्ल्या शहर" },
    taluk:   { en: "Sullia",      kn: "ಸುಳ್ಯ",      hi: "सुल्ल्या" },
    district:{ en: "Dakshina Kannada", kn: "ದಕ್ಷಿಣ ಕನ್ನಡ", hi: "दक्षिण कन्नड" },
    experience: 3,
    availability: "Available",
    phone: "+91 96060 44123",
    languages: ["Kannada", "Tulu"],
    workingHours: "8 AM – 4 PM",
    description: {
      en: "Reliable and hardworking cleaner for homes, offices, and commercial spaces. Brings own equipment. References available.",
      kn: "ಮನೆ, ಕಚೇರಿ ಮತ್ತು ವಾಣಿಜ್ಯ ಜಾಗಗಳಿಗೆ ವಿಶ್ವಾಸಾರ್ಹ ಮತ್ತು ಶ್ರಮಿಕ ಸ್ವಚ್ಛತಾ ಕೆಲಸಗಾರ. ತಮ್ಮ ಉಪಕರಣಗಳನ್ನು ತರುತ್ತಾರೆ.",
      hi: "घर, कार्यालय और व्यावसायिक स्थानों के लिए विश्वसनीय और मेहनती सफाईकर्मी। अपने उपकरण लाते हैं।",
    },
    avatar: "MN",
  },
  {
    id: 5,
    name: { en: "Suresh Gowda", kn: "ಸುರೇಶ್ ಗೌಡ", hi: "सुरेश गौड़ा" },
    skill: "Electrician",
    village: { en: "Bantwal Town", kn: "ಬಂಟ್ವಾಳ ಪಟ್ಟಣ", hi: "बंटवाल शहर" },
    taluk:   { en: "Bantwal",      kn: "ಬಂಟ್ವಾಳ",       hi: "बंटवाल" },
    district:{ en: "Dakshina Kannada", kn: "ದಕ್ಷಿಣ ಕನ್ನಡ", hi: "दक्षिण कन्नड" },
    experience: 10,
    availability: "Available",
    phone: "+91 93426 55478",
    languages: ["Kannada", "Hindi", "English"],
    workingHours: "8 AM – 7 PM",
    description: {
      en: "Certified electrician with experience in domestic wiring, switchboard installation, and electrical repairs. Emergency services available.",
      kn: "ಗೃಹ ವಯರಿಂಗ್, ಸ್ವಿಚ್‌ಬೋರ್ಡ್ ಅಳವಡಿಕೆ ಮತ್ತು ವಿದ್ಯುತ್ ದುರಸ್ತಿಯಲ್ಲಿ ಅನುಭವ ಹೊಂದಿರುವ ಪ್ರಮಾಣಿತ ವಿದ್ಯುತ್ ತಜ್ಞ. ತುರ್ತು ಸೇವೆ ಲಭ್ಯ.",
      hi: "घरेलू वायरिंग, स्विचबोर्ड इंस्टॉलेशन और बिजली मरम्मत में अनुभवी प्रमाणित बिजली मिस्त्री। आपातकालीन सेवा उपलब्ध।",
    },
    avatar: "SG",
  },
  {
    id: 6,
    name: { en: "Priya Kumari", kn: "ಪ್ರಿಯಾ ಕುಮಾರಿ", hi: "प्रिया कुमारी" },
    skill: "Painter",
    village: { en: "Belthangady", kn: "ಬೆಳ್ತಂಗಡಿ",  hi: "बेलतंगडी" },
    taluk:   { en: "Belthangady", kn: "ಬೆಳ್ತಂಗಡಿ",  hi: "बेलतंगडी" },
    district:{ en: "Dakshina Kannada", kn: "ದಕ್ಷಿಣ ಕನ್ನಡ", hi: "दक्षिण कन्नड" },
    experience: 4,
    availability: "Busy",
    phone: "+91 98440 33217",
    languages: ["Kannada", "Hindi"],
    workingHours: "9 AM – 6 PM",
    description: {
      en: "Interior and exterior painter with experience in texture painting, wall designs, and waterproofing. Neat and quality work guaranteed.",
      kn: "ಟೆಕ್ಸ್ಚರ್ ಪೇಂಟಿಂಗ್, ಗೋಡೆ ವಿನ್ಯಾಸ ಮತ್ತು ವಾಟರ್‌ಪ್ರೂಫಿಂಗ್‌ನಲ್ಲಿ ಅನುಭವ ಹೊಂದಿರುವ ಒಳಾಂಗಣ ಮತ್ತು ಹೊರಾಂಗಣ ಬಣ್ಣ ಕೆಲಸಗಾರ.",
      hi: "टेक्सचर पेंटिंग, दीवार डिजाइन और वाटरप्रूफिंग में अनुभवी इंटीरियर और एक्सटीरियर पेंटर।",
    },
    avatar: "PK",
  },
];

export const MOCK_REQUESTS: HireRequest[] = [
  {
    id: 1,
    employerName: { en: "Ramesh Shetty",  kn: "ರಮೇಶ್ ಶೆಟ್ಟಿ",  hi: "रमेश शेट्टी" },
    workType: "Mason",
    location: { en: "Udupi", kn: "ಉಡುಪಿ", hi: "उडुपी" },
    date: "2026-05-28",
    status: "pending",
    message: {
      en: "Need a mason for 2 weeks for house construction. Can start Monday.",
      kn: "ಮನೆ ನಿರ್ಮಾಣಕ್ಕೆ 2 ವಾರಗಳ ಕಟ್ಟಡ ಕೆಲಸಗಾರ ಬೇಕು. ಸೋಮವಾರ ಪ್ರಾರಂಭಿಸಬಹುದು.",
      hi: "घर निर्माण के लिए 2 सप्ताह के लिए राजमिस्त्री चाहिए। सोमवार से शुरू कर सकते हैं।",
    },
  },
  {
    id: 2,
    employerName: { en: "Kavitha Rao",  kn: "ಕವಿತಾ ರಾವ್",  hi: "कविता राव" },
    workType: "Mason",
    location: { en: "Manipal", kn: "ಮಣಿಪಾಲ", hi: "मणिपाल" },
    date: "2026-05-25",
    status: "accepted",
    message: {
      en: "Small tiling job, 2–3 days work. Please bring tools.",
      kn: "ಸಣ್ಣ ಟೈಲಿಂಗ್ ಕೆಲಸ, 2–3 ದಿನ. ದಯವಿಟ್ಟು ಉಪಕರಣಗಳನ್ನು ತನ್ನಿ.",
      hi: "छोटा टाइलिंग काम, 2–3 दिन। कृपया औजार लेकर आएं।",
    },
  },
  {
    id: 3,
    employerName: { en: "Mohan Bhat",  kn: "ಮೋಹನ್ ಭಟ್",  hi: "मोहन भट्ट" },
    workType: "Mason",
    location: { en: "Kundapur", kn: "ಕುಂದಾಪುರ", hi: "कुंदापुर" },
    date: "2026-05-20",
    status: "expired",
    message: {
      en: "Urgent compound wall work. Need to start this week.",
      kn: "ತುರ್ತು ಕಾಂಪೌಂಡ್ ಗೋಡೆ ಕೆಲಸ. ಈ ವಾರ ಪ್ರಾರಂಭಿಸಬೇಕು.",
      hi: "तत्काल कंपाउंड वॉल का काम। इस सप्ताह शुरू करना होगा।",
    },
  },
];

// ─── Translation keys & table ───────────────────────────────────────────────

export type TranslationKey =
  | "appName" | "home" | "findWorkers" | "registerWorker" | "aboutUs"
  | "getStarted" | "heroTitle" | "heroSubtitle" | "heroTagline"
  | "imWorker" | "imEmployer" | "howItWorks"
  | "step1Title" | "step1Desc" | "step2Title" | "step2Desc" | "step3Title" | "step3Desc"
  | "registerTitle" | "registerSubtitle"
  | "fullName" | "contactNumber" | "village" | "taluk" | "district"
  | "experience" | "skillType" | "availability" | "workingHours"
  | "register" | "registrationSuccess" | "registrationSuccessDesc"
  | "findWorkersTitle" | "findWorkersSubtitle" | "workersFound"
  | "contact" | "bookRequest" | "available" | "busy" | "years"
  | "languagesKnown" | "phoneNumber" | "sendRequest"
  | "dashboard" | "incomingRequests" | "accept" | "reject"
  | "editProfile" | "requestHistory" | "myProfile" | "toggleAvailability"
  | "heroTagline" | "trustedWorkers" | "trustedWorkersDesc"
  | "quickConnect" | "quickConnectDesc" | "multiLanguage" | "multiLanguageDesc"
  | "workersRegistered" | "employersConnected" | "taluks" | "skills"
  | "backToHome" | "backToWorkers" | "clearFilters" | "noWorkersFound" | "tryAdjusting"
  | "noPendingRequests" | "newRequestsHere" | "noHistory"
  | "sendHireRequest" | "yourMessage" | "describeWork" | "cancel" | "requestSentTitle" | "requestSentDesc"
  | "viewDashboard" | "allSkills" | "filters"
  | "loginTitle" | "loginSubtitle" | "emailOrPhone" | "password" | "loginBtn"
  | "orContinueWith" | "googleLogin" | "noAccount" | "registerHere" | "forgotPassword"
  | "welcomeBack" | "enterCredentials" | "visibleToEmployers" | "hiddenFromSearch"
  | "pending" | "accepted" | "rejected" | "expired"
  | "location" | "workingHoursLabel" | "selectSkill" | "selectAvailability"
  | "personalInfo" | "locationSection" | "workDetails" | "workingHoursSection"
  | "namePlaceholder" | "phonePlaceholder" | "villagePlaceholder"
  | "talukPlaceholder" | "districtPlaceholder" | "experiencePlaceholder" | "workingHoursPlaceholder"
  | "aboutUsTitle" | "aboutUsBody"
  | "whyRuralUnite" | "readyToStart" | "readyDesc" | "joinThousands"
  | "statsWorkers" | "statsEmployers" | "statsTaluks" | "statsSkills"
  | "requestExpiry" | "voiceInputSoon";

export const translations: Record<Language, Record<TranslationKey, string>> = {
  en: {
    appName: "RuralUnite",
    home: "Home",
    findWorkers: "Find Workers",
    registerWorker: "Register as Worker",
    aboutUs: "About Us",
    getStarted: "Get Started",
    heroTitle: "Connecting Rural Workers with Opportunities",
    heroSubtitle: "Find skilled workers nearby or register your skills. Simple, fast, and trusted by thousands across Karnataka.",
    heroTagline: "Simple • Trusted • Local",
    imWorker: "I'm a Worker",
    imEmployer: "I'm an Employer",
    howItWorks: "How It Works",
    step1Title: "Workers Register",
    step1Desc: "Register your skills, location, and availability in minutes.",
    step2Title: "Employers Search",
    step2Desc: "Find skilled workers nearby by skill type and location.",
    step3Title: "Connect & Grow",
    step3Desc: "Connect directly and start working together.",
    registerTitle: "Register as Worker",
    registerSubtitle: "Fill in your details to start receiving work requests.",
    fullName: "Full Name",
    contactNumber: "Contact Number",
    village: "Village",
    taluk: "Taluk",
    district: "District",
    experience: "Experience (Years)",
    skillType: "Skill Type",
    availability: "Availability",
    workingHours: "Working Hours",
    register: "Register Now",
    registrationSuccess: "Registration Successful!",
    registrationSuccessDesc: "Your profile has been created. Employers in your area can now find and contact you.",
    findWorkersTitle: "Find Workers Near You",
    findWorkersSubtitle: "Browse skilled workers in your area. Filter by skill, location, and availability.",
    workersFound: "workers found",
    contact: "Contact",
    bookRequest: "Send Request",
    available: "Available",
    busy: "Busy",
    years: "yrs exp",
    languagesKnown: "Languages Known",
    phoneNumber: "Phone Number",
    sendRequest: "Send Hire Request",
    dashboard: "My Dashboard",
    incomingRequests: "Incoming Requests",
    accept: "Accept",
    reject: "Reject",
    editProfile: "Edit Profile",
    requestHistory: "Request History",
    myProfile: "My Profile",
    toggleAvailability: "Toggle Availability",
    trustedWorkers: "Trusted Local Workers",
    trustedWorkersDesc: "All workers are verified community members.",
    quickConnect: "Quick Connect",
    quickConnectDesc: "Contact workers directly without any middlemen.",
    multiLanguage: "Multi-Language",
    multiLanguageDesc: "Available in Kannada, Hindi, and English.",
    workersRegistered: "Workers Registered",
    employersConnected: "Employers Connected",
    taluks: "Taluks Covered",
    skills: "Skill Categories",
    backToHome: "Back to Home",
    backToWorkers: "Back to Workers",
    clearFilters: "Clear all filters",
    noWorkersFound: "No workers found",
    tryAdjusting: "Try adjusting your filters",
    noPendingRequests: "No pending requests",
    newRequestsHere: "New requests will appear here",
    noHistory: "No request history",
    sendHireRequest: "Send Hire Request",
    yourMessage: "Your message (optional)",
    describeWork: "Describe the work you need...",
    cancel: "Cancel",
    requestSentTitle: "Request Sent!",
    requestSentDesc: "will receive your request. Expires in 24 hours if not responded to.",
    viewDashboard: "View My Dashboard",
    allSkills: "All Skills",
    filters: "Filters",
    loginTitle: "Welcome to RuralUnite",
    loginSubtitle: "Login to continue",
    emailOrPhone: "Email or Phone Number",
    password: "Password",
    loginBtn: "Login",
    orContinueWith: "or continue with",
    googleLogin: "Continue with Google",
    noAccount: "Don't have an account?",
    registerHere: "Register here",
    forgotPassword: "Forgot password?",
    welcomeBack: "Welcome Back",
    enterCredentials: "Enter your credentials to login",
    visibleToEmployers: "Visible to employers",
    hiddenFromSearch: "Hidden from search",
    pending: "Pending",
    accepted: "Accepted",
    rejected: "Rejected",
    expired: "Expired",
    location: "Location",
    workingHoursLabel: "Working Hours",
    selectSkill: "Select your skill",
    selectAvailability: "Select availability",
    personalInfo: "Personal Information",
    locationSection: "Location",
    workDetails: "Work Details",
    workingHoursSection: "Working Hours",
    namePlaceholder: "e.g. Ravi Poojary",
    phonePlaceholder: "+91 9XXXXXXXXX",
    villagePlaceholder: "Your village name",
    talukPlaceholder: "Taluk",
    districtPlaceholder: "District",
    experiencePlaceholder: "e.g. 5",
    workingHoursPlaceholder: "e.g. 8 AM – 6 PM",
    aboutUsTitle: "About Us",
    aboutUsBody: "RuralUnite is a simple platform built to connect skilled rural workers with people who need trusted services nearby. Many talented workers in villages and small towns struggle to find opportunities, while customers often find it difficult to discover reliable local workers quickly.\n\nOur goal is to bridge this gap using technology that is simple, accessible, and easy to use for everyone.\n\nRuralUnite helps workers showcase their skills, availability, and experience, while allowing employers and customers to search and connect with workers in their local areas. The platform is designed with multilingual support and a clean user-friendly interface so that even first-time digital users can use it comfortably.\n\nWe believe technology should not only serve cities — it should also empower rural communities, create opportunities, and help skilled workers grow with dignity and visibility.\n\nRuralUnite is a step towards building stronger local connections, improving access to work opportunities, and supporting rural talent through simple digital solutions.",
    whyRuralUnite: "Why RuralUnite?",
    readyToStart: "Ready to get started?",
    readyDesc: "Join thousands of workers and employers already connected on RuralUnite.",
    joinThousands: "Join now",
    statsWorkers: "Workers Registered",
    statsEmployers: "Employers Connected",
    statsTaluks: "Taluks Covered",
    statsSkills: "Skill Categories",
    requestExpiry: "Requests expire automatically after 24 hours if not responded to.",
    voiceInputSoon: "Voice input (coming soon)",
  },
  kn: {
    appName: "ರೂರಲ್‌ಯುನೈಟ್",
    home: "ಮುಖಪುಟ",
    findWorkers: "ಕೆಲಸಗಾರರನ್ನು ಹುಡುಕಿ",
    registerWorker: "ಕೆಲಸಗಾರರಾಗಿ ನೋಂದಾಯಿಸಿ",
    aboutUs: "ನಮ್ಮ ಬಗ್ಗೆ",
    getStarted: "ಪ್ರಾರಂಭಿಸಿ",
    heroTitle: "ಗ್ರಾಮೀಣ ಕೆಲಸಗಾರರನ್ನು ಅವಕಾಶಗಳೊಂದಿಗೆ ಜೋಡಿಸುವುದು",
    heroSubtitle: "ಹತ್ತಿರದ ಕುಶಲ ಕೆಲಸಗಾರರನ್ನು ಹುಡುಕಿ ಅಥವಾ ನಿಮ್ಮ ಕೌಶಲ್ಯಗಳನ್ನು ನೋಂದಾಯಿಸಿ.",
    heroTagline: "ಸರಳ • ವಿಶ್ವಾಸಾರ್ಹ • ಸ್ಥಳೀಯ",
    imWorker: "ನಾನು ಕೆಲಸಗಾರ",
    imEmployer: "ನಾನು ಉದ್ಯೋಗದಾತ",
    howItWorks: "ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ",
    step1Title: "ಕೆಲಸಗಾರರು ನೋಂದಾಯಿಸಿ",
    step1Desc: "ನಿಮ್ಮ ಕೌಶಲ್ಯ, ಸ್ಥಳ ಮತ್ತು ಲಭ್ಯತೆಯನ್ನು ನಿಮಿಷಗಳಲ್ಲಿ ನೋಂದಾಯಿಸಿ.",
    step2Title: "ಉದ್ಯೋಗದಾತರು ಹುಡುಕಿ",
    step2Desc: "ಕೌಶಲ್ಯ ಮತ್ತು ಸ್ಥಳದ ಮೂಲಕ ಹತ್ತಿರದ ಕುಶಲ ಕೆಲಸಗಾರರನ್ನು ಹುಡುಕಿ.",
    step3Title: "ಸಂಪರ್ಕಿಸಿ ಮತ್ತು ಬೆಳೆಯಿರಿ",
    step3Desc: "ನೇರವಾಗಿ ಸಂಪರ್ಕಿಸಿ ಮತ್ತು ಒಟ್ಟಿಗೆ ಕೆಲಸ ಪ್ರಾರಂಭಿಸಿ.",
    registerTitle: "ಕೆಲಸಗಾರರಾಗಿ ನೋಂದಾಯಿಸಿ",
    registerSubtitle: "ಕೆಲಸದ ವಿನಂತಿಗಳನ್ನು ಪಡೆಯಲು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ.",
    fullName: "ಪೂರ್ಣ ಹೆಸರು",
    contactNumber: "ಸಂಪರ್ಕ ಸಂಖ್ಯೆ",
    village: "ಊರು",
    taluk: "ತಾಲೂಕು",
    district: "ಜಿಲ್ಲೆ",
    experience: "ಅನುಭವ (ವರ್ಷಗಳು)",
    skillType: "ಕೌಶಲ್ಯ ವಿಧ",
    availability: "ಲಭ್ಯತೆ",
    workingHours: "ಕೆಲಸದ ಸಮಯ",
    register: "ಈಗ ನೋಂದಾಯಿಸಿ",
    registrationSuccess: "ನೋಂದಣಿ ಯಶಸ್ವಿಯಾಗಿದೆ!",
    registrationSuccessDesc: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ರಚಿಸಲಾಗಿದೆ. ನಿಮ್ಮ ಪ್ರದೇಶದ ಉದ್ಯೋಗದಾತರು ಈಗ ನಿಮ್ಮನ್ನು ಕಂಡುಹಿಡಿಯಬಹುದು.",
    findWorkersTitle: "ಹತ್ತಿರದ ಕೆಲಸಗಾರರನ್ನು ಹುಡುಕಿ",
    findWorkersSubtitle: "ನಿಮ್ಮ ಪ್ರದೇಶದ ಕುಶಲ ಕೆಲಸಗಾರರನ್ನು ಹುಡುಕಿ.",
    workersFound: "ಕೆಲಸಗಾರರು ಕಂಡುಬಂದಿದ್ದಾರೆ",
    contact: "ಸಂಪರ್ಕಿಸಿ",
    bookRequest: "ವಿನಂತಿ ಕಳುಹಿಸಿ",
    available: "ಲಭ್ಯ",
    busy: "ಬ್ಯುಸಿ",
    years: "ವರ್ಷ ಅನುಭವ",
    languagesKnown: "ತಿಳಿದಿರುವ ಭಾಷೆಗಳು",
    phoneNumber: "ಫೋನ್ ಸಂಖ್ಯೆ",
    sendRequest: "ನೇಮಕ ವಿನಂತಿ ಕಳುಹಿಸಿ",
    dashboard: "ನನ್ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    incomingRequests: "ಬರುತ್ತಿರುವ ವಿನಂತಿಗಳು",
    accept: "ಒಪ್ಪಿಕೊಳ್ಳಿ",
    reject: "ತಿರಸ್ಕರಿಸಿ",
    editProfile: "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
    requestHistory: "ವಿನಂತಿ ಇತಿಹಾಸ",
    myProfile: "ನನ್ನ ಪ್ರೊಫೈಲ್",
    toggleAvailability: "ಲಭ್ಯತೆ ಬದಲಾಯಿಸಿ",
    trustedWorkers: "ವಿಶ್ವಾಸಾರ್ಹ ಸ್ಥಳೀಯ ಕೆಲಸಗಾರರು",
    trustedWorkersDesc: "ಎಲ್ಲಾ ಕೆಲಸಗಾರರು ಸಮುದಾಯ ಸದಸ್ಯರು.",
    quickConnect: "ತ್ವರಿತ ಸಂಪರ್ಕ",
    quickConnectDesc: "ಮಧ್ಯವರ್ತಿಗಳಿಲ್ಲದೆ ನೇರವಾಗಿ ಸಂಪರ್ಕಿಸಿ.",
    multiLanguage: "ಬಹು-ಭಾಷೆ",
    multiLanguageDesc: "ಕನ್ನಡ, ಹಿಂದಿ ಮತ್ತು ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಲಭ್ಯ.",
    workersRegistered: "ನೋಂದಾಯಿತ ಕೆಲಸಗಾರರು",
    employersConnected: "ಸಂಪರ್ಕಿತ ಉದ್ಯೋಗದಾತರು",
    taluks: "ತಾಲೂಕುಗಳು",
    skills: "ಕೌಶಲ್ಯ ವರ್ಗಗಳು",
    backToHome: "ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ",
    backToWorkers: "ಕೆಲಸಗಾರರಿಗೆ ಹಿಂತಿರುಗಿ",
    clearFilters: "ಎಲ್ಲಾ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ",
    noWorkersFound: "ಯಾವುದೇ ಕೆಲಸಗಾರರು ಕಂಡುಬಂದಿಲ್ಲ",
    tryAdjusting: "ನಿಮ್ಮ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಸರಿಪಡಿಸಲು ಪ್ರಯತ್ನಿಸಿ",
    noPendingRequests: "ಯಾವುದೇ ಬಾಕಿ ವಿನಂತಿಗಳಿಲ್ಲ",
    newRequestsHere: "ಹೊಸ ವಿನಂತಿಗಳು ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತವೆ",
    noHistory: "ಯಾವುದೇ ವಿನಂತಿ ಇತಿಹಾಸವಿಲ್ಲ",
    sendHireRequest: "ನೇಮಕ ವಿನಂತಿ ಕಳುಹಿಸಿ",
    yourMessage: "ನಿಮ್ಮ ಸಂದೇಶ (ಐಚ್ಛಿಕ)",
    describeWork: "ನಿಮಗೆ ಅಗತ್ಯವಿರುವ ಕೆಲಸವನ್ನು ವಿವರಿಸಿ...",
    cancel: "ರದ್ದು",
    requestSentTitle: "ವಿನಂತಿ ಕಳುಹಿಸಲಾಗಿದೆ!",
    requestSentDesc: "ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ಸ್ವೀಕರಿಸುತ್ತಾರೆ. ಪ್ರತಿಕ್ರಿಯೆ ನೀಡದಿದ್ದರೆ 24 ಗಂಟೆಗಳ ನಂತರ ಅವಧಿ ಮುಗಿಯುತ್ತದೆ.",
    viewDashboard: "ನನ್ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ವೀಕ್ಷಿಸಿ",
    allSkills: "ಎಲ್ಲಾ ಕೌಶಲ್ಯಗಳು",
    filters: "ಫಿಲ್ಟರ್‌ಗಳು",
    loginTitle: "ರೂರಲ್‌ಯುನೈಟ್‌ಗೆ ಸ್ವಾಗತ",
    loginSubtitle: "ಮುಂದುವರಿಯಲು ಲಾಗಿನ್ ಮಾಡಿ",
    emailOrPhone: "ಇಮೇಲ್ ಅಥವಾ ಫೋನ್ ಸಂಖ್ಯೆ",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    loginBtn: "ಲಾಗಿನ್",
    orContinueWith: "ಅಥವಾ ಇದರ ಮೂಲಕ ಮುಂದುವರಿಯಿರಿ",
    googleLogin: "Google ಮೂಲಕ ಮುಂದುವರಿಯಿರಿ",
    noAccount: "ಖಾತೆ ಇಲ್ಲವೇ?",
    registerHere: "ಇಲ್ಲಿ ನೋಂದಾಯಿಸಿ",
    forgotPassword: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?",
    welcomeBack: "ಮತ್ತೆ ಸ್ವಾಗತ",
    enterCredentials: "ಲಾಗಿನ್ ಮಾಡಲು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
    visibleToEmployers: "ಉದ್ಯೋಗದಾತರಿಗೆ ಗೋಚರ",
    hiddenFromSearch: "ಹುಡುಕಾಟದಿಂದ ಮರೆಮಾಡಲಾಗಿದೆ",
    pending: "ಬಾಕಿ",
    accepted: "ಒಪ್ಪಿಗೆ",
    rejected: "ತಿರಸ್ಕೃತ",
    expired: "ಅವಧಿ ಮೀರಿದೆ",
    location: "ಸ್ಥಳ",
    workingHoursLabel: "ಕೆಲಸದ ಸಮಯ",
    selectSkill: "ನಿಮ್ಮ ಕೌಶಲ್ಯ ಆಯ್ಕೆ ಮಾಡಿ",
    selectAvailability: "ಲಭ್ಯತೆ ಆಯ್ಕೆ ಮಾಡಿ",
    personalInfo: "ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ",
    locationSection: "ಸ್ಥಳ",
    workDetails: "ಕೆಲಸದ ವಿವರಗಳು",
    workingHoursSection: "ಕೆಲಸದ ಸಮಯ",
    namePlaceholder: "ಉದಾ. ರವಿ ಪೂಜಾರಿ",
    phonePlaceholder: "+91 9XXXXXXXXX",
    villagePlaceholder: "ನಿಮ್ಮ ಊರಿನ ಹೆಸರು",
    talukPlaceholder: "ತಾಲೂಕು",
    districtPlaceholder: "ಜಿಲ್ಲೆ",
    experiencePlaceholder: "ಉದಾ. 5",
    workingHoursPlaceholder: "ಉದಾ. ಬೆಳಿಗ್ಗೆ 8 – ಸಂಜೆ 6",
    aboutUsTitle: "ನಮ್ಮ ಬಗ್ಗೆ",
    aboutUsBody: "ರೂರಲ್‌ಯುನೈಟ್ ಎನ್ನುವುದು ಕುಶಲ ಗ್ರಾಮೀಣ ಕೆಲಸಗಾರರನ್ನು ಹತ್ತಿರದ ವಿಶ್ವಾಸಾರ್ಹ ಸೇವೆಗಳ ಅಗತ್ಯ ಹೊಂದಿರುವವರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಲು ನಿರ್ಮಿಸಲಾದ ಒಂದು ಸರಳ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್. ಊರು ಮತ್ತು ಸಣ್ಣ ಪಟ್ಟಣಗಳಲ್ಲಿ ಅನೇಕ ಪ್ರತಿಭಾವಂತ ಕೆಲಸಗಾರರು ಅವಕಾಶಗಳನ್ನು ಹುಡುಕುವಲ್ಲಿ ತೊಂದರೆ ಅನುಭವಿಸುತ್ತಾರೆ, ಆದರೆ ಗ್ರಾಹಕರಿಗೆ ವಿಶ್ವಾಸಾರ್ಹ ಸ್ಥಳೀಯ ಕೆಲಸಗಾರರನ್ನು ತ್ವರಿತವಾಗಿ ಕಂಡುಹಿಡಿಯುವುದು ಕಷ್ಟವಾಗಿರುತ್ತದೆ.\n\nಈ ಅಂತರವನ್ನು ಸರಳ, ಸಾಧ್ಯ ಮತ್ತು ಎಲ್ಲರಿಗೂ ಉಪಯೋಗಿಸಲು ಸುಲಭವಾದ ತಂತ್ರಜ್ಞಾನ ಬಳಸಿ ಸೇತುವೆ ನಿರ್ಮಿಸುವುದು ನಮ್ಮ ಗುರಿ.\n\nರೂರಲ್‌ಯುನೈಟ್ ಕೆಲಸಗಾರರಿಗೆ ತಮ್ಮ ಕೌಶಲ್ಯ, ಲಭ್ಯತೆ ಮತ್ತು ಅನುಭವವನ್ನು ತೋರಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ, ಜೊತೆಗೆ ಉದ್ಯೋಗದಾತರು ಮತ್ತು ಗ್ರಾಹಕರಿಗೆ ತಮ್ಮ ಸ್ಥಳೀಯ ಪ್ರದೇಶದಲ್ಲಿ ಕೆಲಸಗಾರರನ್ನು ಹುಡುಕಿ ಸಂಪರ್ಕಿಸಲು ಅನುವು ಮಾಡಿಕೊಡುತ್ತದೆ.\n\nತಂತ್ರಜ್ಞಾನ ಕೇವಲ ನಗರಗಳಿಗೆ ಮಾತ್ರ ಅಲ್ಲ — ಅದು ಗ್ರಾಮೀಣ ಸಮುದಾಯಗಳನ್ನು ಸಶಕ್ತಗೊಳಿಸಬೇಕು ಮತ್ತು ಕುಶಲ ಕೆಲಸಗಾರರು ಗೌರವ ಮತ್ತು ಗೋಚರತೆಯೊಂದಿಗೆ ಬೆಳೆಯಲು ಸಹಾಯ ಮಾಡಬೇಕು ಎಂದು ನಾವು ನಂಬುತ್ತೇವೆ.\n\nರೂರಲ್‌ಯುನೈಟ್ ಬಲವಾದ ಸ್ಥಳೀಯ ಸಂಪರ್ಕಗಳನ್ನು ನಿರ್ಮಿಸಲು, ಕೆಲಸದ ಅವಕಾಶಗಳಿಗೆ ಪ್ರವೇಶ ಸುಧಾರಿಸಲು ಮತ್ತು ಸರಳ ಡಿಜಿಟಲ್ ಪರಿಹಾರಗಳ ಮೂಲಕ ಗ್ರಾಮೀಣ ಪ್ರತಿಭೆಯನ್ನು ಬೆಂಬಲಿಸಲು ಒಂದು ಹೆಜ್ಜೆಯಾಗಿದೆ.",
    whyRuralUnite: "ರೂರಲ್‌ಯುನೈಟ್ ಏಕೆ?",
    readyToStart: "ಪ್ರಾರಂಭಿಸಲು ಸಿದ್ಧರಿದ್ದೀರಾ?",
    readyDesc: "ರೂರಲ್‌ಯುನೈಟ್‌ನಲ್ಲಿ ಈಗಾಗಲೇ ಸಂಪರ್ಕಿಸಲಾದ ಸಾವಿರಾರು ಕೆಲಸಗಾರರು ಮತ್ತು ಉದ್ಯೋಗದಾತರೊಂದಿಗೆ ಸೇರಿ.",
    joinThousands: "ಈಗ ಸೇರಿ",
    statsWorkers: "ನೋಂದಾಯಿತ ಕೆಲಸಗಾರರು",
    statsEmployers: "ಸಂಪರ್ಕಿತ ಉದ್ಯೋಗದಾತರು",
    statsTaluks: "ತಾಲೂಕುಗಳು",
    statsSkills: "ಕೌಶಲ್ಯ ವರ್ಗಗಳು",
    requestExpiry: "ಪ್ರತಿಕ್ರಿಯೆ ನೀಡದಿದ್ದರೆ 24 ಗಂಟೆಗಳ ನಂತರ ವಿನಂತಿಗಳು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಅವಧಿ ಮೀರುತ್ತವೆ.",
    voiceInputSoon: "ಧ್ವನಿ ಇನ್‌ಪುಟ್ (ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ)",
  },
  hi: {
    appName: "रूरलयूनाइट",
    home: "होम",
    findWorkers: "कामगार खोजें",
    registerWorker: "कामगार के रूप में पंजीकरण",
    aboutUs: "हमारे बारे में",
    getStarted: "शुरू करें",
    heroTitle: "ग्रामीण कामगारों को अवसरों से जोड़ना",
    heroSubtitle: "पास के कुशल कामगार खोजें या अपने कौशल पंजीकृत करें। सरल, तेज़ और विश्वसनीय।",
    heroTagline: "सरल • विश्वसनीय • स्थानीय",
    imWorker: "मैं कामगार हूँ",
    imEmployer: "मैं नियोक्ता हूँ",
    howItWorks: "यह कैसे काम करता है",
    step1Title: "कामगार पंजीकरण करें",
    step1Desc: "मिनटों में अपने कौशल, स्थान और उपलब्धता दर्ज करें।",
    step2Title: "नियोक्ता खोजें",
    step2Desc: "कौशल और स्थान के अनुसार पास के कुशल कामगार खोजें।",
    step3Title: "जुड़ें और बढ़ें",
    step3Desc: "सीधे संपर्क करें और साथ मिलकर काम शुरू करें।",
    registerTitle: "कामगार के रूप में पंजीकरण",
    registerSubtitle: "काम के अनुरोध पाने के लिए अपना विवरण भरें।",
    fullName: "पूरा नाम",
    contactNumber: "संपर्क नंबर",
    village: "गाँव",
    taluk: "तालुक",
    district: "जिला",
    experience: "अनुभव (वर्ष)",
    skillType: "कौशल प्रकार",
    availability: "उपलब्धता",
    workingHours: "काम के घंटे",
    register: "अभी पंजीकरण करें",
    registrationSuccess: "पंजीकरण सफल!",
    registrationSuccessDesc: "आपकी प्रोफ़ाइल बन गई है। आपके क्षेत्र के नियोक्ता अब आपको खोज सकते हैं।",
    findWorkersTitle: "पास के कामगार खोजें",
    findWorkersSubtitle: "अपने क्षेत्र के कुशल कामगार खोजें।",
    workersFound: "कामगार मिले",
    contact: "संपर्क करें",
    bookRequest: "अनुरोध भेजें",
    available: "उपलब्ध",
    busy: "व्यस्त",
    years: "वर्ष अनुभव",
    languagesKnown: "ज्ञात भाषाएं",
    phoneNumber: "फ़ोन नंबर",
    sendRequest: "भर्ती अनुरोध भेजें",
    dashboard: "मेरा डैशबोर्ड",
    incomingRequests: "आने वाले अनुरोध",
    accept: "स्वीकार करें",
    reject: "अस्वीकार करें",
    editProfile: "प्रोफ़ाइल संपादित करें",
    requestHistory: "अनुरोध इतिहास",
    myProfile: "मेरी प्रोफ़ाइल",
    toggleAvailability: "उपलब्धता बदलें",
    trustedWorkers: "विश्वसनीय स्थानीय कामगार",
    trustedWorkersDesc: "सभी कामगार सामुदायिक सदस्य हैं।",
    quickConnect: "त्वरित संपर्क",
    quickConnectDesc: "बिना बिचौलियों के सीधे संपर्क करें।",
    multiLanguage: "बहु-भाषा",
    multiLanguageDesc: "कन्नड़, हिंदी और अंग्रेज़ी में उपलब्ध।",
    workersRegistered: "पंजीकृत कामगार",
    employersConnected: "जुड़े नियोक्ता",
    taluks: "तालुक कवर",
    skills: "कौशल श्रेणियां",
    backToHome: "होम पर वापस जाएं",
    backToWorkers: "कामगारों पर वापस जाएं",
    clearFilters: "सभी फ़िल्टर हटाएं",
    noWorkersFound: "कोई कामगार नहीं मिला",
    tryAdjusting: "अपने फ़िल्टर बदलकर देखें",
    noPendingRequests: "कोई लंबित अनुरोध नहीं",
    newRequestsHere: "नए अनुरोध यहाँ दिखेंगे",
    noHistory: "कोई अनुरोध इतिहास नहीं",
    sendHireRequest: "भर्ती अनुरोध भेजें",
    yourMessage: "आपका संदेश (वैकल्पिक)",
    describeWork: "जो काम चाहिए उसे बताएं...",
    cancel: "रद्द करें",
    requestSentTitle: "अनुरोध भेजा गया!",
    requestSentDesc: "आपका अनुरोध प्राप्त करेंगे। 24 घंटे में जवाब न देने पर अनुरोध समाप्त हो जाएगा।",
    viewDashboard: "मेरा डैशबोर्ड देखें",
    allSkills: "सभी कौशल",
    filters: "फ़िल्टर",
    loginTitle: "रूरलयूनाइट में आपका स्वागत है",
    loginSubtitle: "जारी रखने के लिए लॉगिन करें",
    emailOrPhone: "ईमेल या फ़ोन नंबर",
    password: "पासवर्ड",
    loginBtn: "लॉगिन",
    orContinueWith: "या इससे जारी रखें",
    googleLogin: "Google से जारी रखें",
    noAccount: "खाता नहीं है?",
    registerHere: "यहाँ पंजीकरण करें",
    forgotPassword: "पासवर्ड भूल गए?",
    welcomeBack: "वापस स्वागत है",
    enterCredentials: "लॉगिन के लिए अपनी जानकारी दर्ज करें",
    visibleToEmployers: "नियोक्ताओं को दिखाई देता है",
    hiddenFromSearch: "खोज से छुपाया गया",
    pending: "लंबित",
    accepted: "स्वीकृत",
    rejected: "अस्वीकृत",
    expired: "समाप्त",
    location: "स्थान",
    workingHoursLabel: "काम के घंटे",
    selectSkill: "अपना कौशल चुनें",
    selectAvailability: "उपलब्धता चुनें",
    personalInfo: "व्यक्तिगत जानकारी",
    locationSection: "स्थान",
    workDetails: "काम का विवरण",
    workingHoursSection: "काम के घंटे",
    namePlaceholder: "जैसे: रवि पूजारी",
    phonePlaceholder: "+91 9XXXXXXXXX",
    villagePlaceholder: "आपके गाँव का नाम",
    talukPlaceholder: "तालुक",
    districtPlaceholder: "जिला",
    experiencePlaceholder: "जैसे: 5",
    workingHoursPlaceholder: "जैसे: सुबह 8 – शाम 6",
    aboutUsTitle: "हमारे बारे में",
    aboutUsBody: "रूरलयूनाइट एक सरल प्लेटफ़ॉर्म है जो कुशल ग्रामीण कामगारों को उन लोगों से जोड़ने के लिए बनाया गया है जिन्हें पास में विश्वसनीय सेवाओं की आवश्यकता है। गाँवों और छोटे शहरों में कई प्रतिभाशाली कामगारों को अवसर खोजने में कठिनाई होती है, जबकि ग्राहकों को अक्सर जल्दी से विश्वसनीय स्थानीय कामगार खोजना मुश्किल होता है।\n\nहमारा लक्ष्य इस अंतर को ऐसी तकनीक से पाटना है जो सरल, सुलभ और सभी के लिए उपयोग में आसान हो।\n\nरूरलयूनाइट कामगारों को अपने कौशल, उपलब्धता और अनुभव दिखाने में मदद करता है, साथ ही नियोक्ताओं और ग्राहकों को अपने स्थानीय क्षेत्रों में कामगारों को खोजने और जोड़ने की सुविधा देता है।\n\nहम मानते हैं कि तकनीक केवल शहरों की सेवा नहीं करनी चाहिए — इसे ग्रामीण समुदायों को सशक्त बनाना चाहिए, अवसर पैदा करने चाहिए और कुशल कामगारों को गरिमा और दृश्यता के साथ बढ़ने में मदद करनी चाहिए।\n\nरूरलयूनाइट मजबूत स्थानीय संबंध बनाने, काम के अवसरों तक पहुंच में सुधार करने और सरल डिजिटल समाधानों के माध्यम से ग्रामीण प्रतिभा का समर्थन करने की दिशा में एक कदम है।",
    whyRuralUnite: "रूरलयूनाइट क्यों?",
    readyToStart: "शुरू करने के लिए तैयार हैं?",
    readyDesc: "रूरलयूनाइट पर पहले से जुड़े हजारों कामगारों और नियोक्ताओं के साथ शामिल हों।",
    joinThousands: "अभी जुड़ें",
    statsWorkers: "पंजीकृत कामगार",
    statsEmployers: "जुड़े नियोक्ता",
    statsTaluks: "तालुक कवर",
    statsSkills: "कौशल श्रेणियां",
    requestExpiry: "प्रतिक्रिया न देने पर 24 घंटे बाद अनुरोध स्वचालित रूप से समाप्त हो जाते हैं।",
    voiceInputSoon: "वॉइस इनपुट (जल्द आ रहा है)",
  },
};

export const t = (key: TranslationKey, lang: Language): string =>
  translations[lang]?.[key] ?? translations.en[key] ?? key;
